server.port = 8080
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=sig
spring.data.mongodb.uri=mongodb+srv://natzi:eNZ62ju8ZU0CyKxI@test.hty5q76.mongodb.net/test?retryWrites=true&w=majority




